function cent = maxima(d)
edg = 3;
sd=size(d);
[x y]=find(d(edg:sd(1)-edg,edg:sd(2)-edg));
cent=[];
x=x+edg-1;
y=y+edg-1;
for j=1:length(y)
    if (d(x(j),y(j))>d(x(j)-1,y(j)-1)) &&...
            (d(x(j),y(j))>d(x(j)-1,y(j))) &&...
            (d(x(j),y(j))>d(x(j)-1,y(j)+1)) &&...
            (d(x(j),y(j))>d(x(j),y(j)-1)) && ...
            (d(x(j),y(j))>d(x(j),y(j)+1)) && ...
            (d(x(j),y(j))>d(x(j)+1,y(j)-1)) && ...
            (d(x(j),y(j))>d(x(j)+1,y(j))) && ...
            (d(x(j),y(j))>d(x(j)+1,y(j)+1)) && ...
            (d(x(j),y(j))>d(x(j)-2,y(j))) &&...
            (d(x(j),y(j))>d(x(j),y(j)-2)) &&...
            (d(x(j),y(j))>d(x(j)+2,y(j))) &&...
            (d(x(j),y(j))>d(x(j),y(j)+2));
        cent = [cent ;  y(j) ; x(j)];        
    end
end
